### PR TITLE
Use comma separation for complex deploy options

### LINKED ISSUE #103: Error building while using postdeploy script and include sub-scripts
Hello

i'm having issue to setup project which contains pre/post deployment "sub" scripts included via syntax ":r" or "r:"

```
PRINT 'Permissions...'
GO
r: PostDeployment.GrantPermissions.sql
GO
--PRINT 'Seed data...'
--GO
r: Seeds/_seeds.sql
```

Getting those kind of errors
```
EXEC : warning SQL70501: DML statements cannot be modeled. [C:\Users\foo\Documents\svn\play\SSDT\API.Database\API.Database.csproj]
EXEC : error SQL46010: Incorrect syntax near PostDeployment. [C:\Users\foo\Documents\svn\play\SSDT\API.Database\API.Database.csproj]
EXEC : error SQL46010: Incorrect syntax near Seeds. [C:\Users\foo\Documents\svn\play\SSDT\API.Database\API.Database.csproj]
C:\Users\foo\.nuget\packages\msbuild.sdk.sqlproj\1.10.0\Sdk\Sdk.targets(196,5): error MSB3073: The command "dotnet "C:\Users\foo\.nuget\packages\msbuild.sdk.sqlproj\1.10.0\Sdk\../tools/netcoreapp5.0/DacpacTool.dll" build -o "obj\Debug\netstandard2.0\API.Database.dacpac" -n "API.Database" -v "1.0.0" -sv Sql130 -i "obj\Debug\netstandard2.0\API.Database.InputFiles.txt"  -sc MySqlCmdVariable -p RecoveryMode=Simple  --postdeploy Scripts\PostDeployment.sql  " exited with code 1. [C:\Users\foo\Documents\svn\play\SSDT\API.Database\API.Database.csproj]
    1 Warning(s)
    3 Error(s)
```

I tried syntax ":r" and got `EXEC : error SQL46010: Incorrect syntax near :.

Here my csproj file
```
<Project Sdk="MSBuild.Sdk.SqlProj/1.10.0">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <SqlServerVersion>Sql130</SqlServerVersion>
    <CompatibilityMode>130</CompatibilityMode>
    <RecoveryMode>Simple</RecoveryMode>
    <BackupDatabaseBeforeChanges>True</BackupDatabaseBeforeChanges>
    <BlockOnPossibleDataLoss>True</BlockOnPossibleDataLoss>
    <AnsiNulls>True</AnsiNulls>
    <QuotedIdentifier>True</QuotedIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <!--<Content Remove="Scripts\PostDeployment.sql" />-->
    <PostDeploy Include="Scripts\PostDeployment.sql" />
    <Content Remove="Scripts\PostDeployment.GrantPermissions.sql" />
    <Content Remove="Scripts\identity.sql" />
    <Content Remove="Scripts\identity-live.sql" />
    <Content Remove="Scripts\Changes\**" />
    <Content Remove="Scripts\Seeds\**" />
  </ItemGroup>
  <ItemGroup>
    <SqlCmdVariable Include="InitialLoad">
      <DefaultValue>FALSE</DefaultValue>
      <Value>$(InitialLoad)</Value>
    </SqlCmdVariable>
  </ItemGroup>
</Project>
```

### LINKED ISSUE #104: Publish option ExcludeObjectTypes not working with multiple values
hello

i have issue when setting option to drop objects not in source and trying to preserve security objects for instance Users and Views seems like after semi-column not take value, tried with quotes and double quotes without success. When setting one object type works!
```
 dotnet publish /p:TargetDatabaseName=API_clean /p:DropObjectsNotInSource=True /p:ExcludeObjectTypes=Users;Views /p:BlockOnPossibleDataLoss=False
...
Setting property DropObjectsNotInSource to value True
  Setting property ExcludeObjectTypes to value Users
...
 Dropping Permission...
  Dropping [dbo].[aaa]...
  Dropping [dbo].[V_aaaCustomer]...
...
```
With sqlpackage.exe it does work but use different sets of flags
```
    <DoNotDropRoutes>True</DoNotDropRoutes>
    <DoNotDropRules>True</DoNotDropRules>
    <DoNotDropUsers>True</DoNotDropUsers>
    <DoNotDropSignatures>True</DoNotDropSignatures>
```

thanks in advance for your help

### PR DESCRIPTION
**Pull request by jmezach**
Due to how semi-colons are parsed by shells the previous implementation using a semi-colon separated list of values doesn't actually work. I've now changed this to be comma separated instead. As discussed in #104 this is technically a breaking change, but since the old implementation didn't work either I don't think we have to sweat it.

I've also added the clarification discussed in #103 about `dotnet publish` support being targetted at developers updating their local databases and we suggest using SqlPackage.exe for more advanced scenario's .

Fixes #104 
Fixes #103

### CODE REVIEW

File: src/DacpacTool/PackageDeployer.cs [hunk 1]
```diff
@@ -333,7 +345,12 @@ private ObjectType[] ParseObjectTypes(string value)
 
         private DacAzureDatabaseSpecification ParseDatabaseSpecification(string value)
         {
-            var specification = value.Split(";", 3);
+            if (value.Contains(';'))
```
Comment (ErikEJ) [inline src/DacpacTool/PackageDeployer.cs:348]: Mind your strings: https://www.google.com/amp/s/jimmybogard.com/mind-your-strings-with-net-5-0/amp/

**Review by ErikEJ — CHANGES_REQUESTED** [review]

File: src/DacpacTool/PackageDeployer.cs (hunk 1 above)
Comment (jmezach) [reply src/DacpacTool/PackageDeployer.cs:348]: ;) The certificate on that site has expired it seems.

Comment (ErikEJ) [reply src/DacpacTool/PackageDeployer.cs:348]: Use StringComparision overload

Comment (jmezach) [reply src/DacpacTool/PackageDeployer.cs]: Ah, right, yeah that makes sense :).

**Comment by jmezach** [comment]
@ErikEJ Could you have another look here?

**Review by ErikEJ — APPROVED** [review]

**Review by jeffrosenberg — APPROVED** [review]

File: README.md [hunk 2]
```diff
@@ -313,7 +313,9 @@ You can now reference your dacpac as a `PackageReference`!
...
 
 ## Publishing support
-Starting with version 1.2.0 of MSBuild.Sdk.SqlProj there is support for publishing a project to a SQL Server using the `dotnet publish` command. There are a couple of properties that control the deployment process which have some defaults to make the experience as smooth as possible for local development. For example, on Windows if you have a default SQL Server instance running on your local machine running `dotnet publish` creates a database with the same name as the project. Unfortunately on Mac and Linux we cannot use Windows authentication, so you'll need to specify a username and password:
+Starting with version 1.2.0 of MSBuild.Sdk.SqlProj there is support for publishing a project to a SQL Server using the `dotnet publish` command. This support is designed to be used by developers to deploy or update their local development database quickly. For more advanced deployment scenario's we suggest using [SqlPackage.exe](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage?view=sql-server-ver15) instead as it provides more options.
```
[the remark this answers is not in the document]
Comment (jmezach) [reply README.md:316]: Yes, I think so too. Not that we're overwhelmed with feature requests or anything (although that may change next week after I've appeared on the EF Core Community Standup ;)), but it is good to have something to fallback on.
