### PR TITLE
Fix logging of DacModelExceptions

### LINKED ISSUE #734: Issues with the Error List pane in Visual Studio
I'm noticing a couple of issues with the Error List pane in Visual Studio.

Image

For one, when you double click on an error it doesn't take you to the file.

Secondly, the Path column doesn't show the correct value. It's showing the path to the root of the database project, not the path to the erroring SQL script file. For example, in the screenshot above you can see the DistressSource.sql script shows the path as: C:\Dev\RPR\Databases\StaticData, however the build output shows the correct path:

> 1>Adding C:\Dev\RPR\Databases\StaticData\reference\StaticData\DistressSource.sql to the model
> 1>DistressSource.sql(1,1): error SQL46010: Incorrect syntax near '\'.

### PR DESCRIPTION
**Pull request by ErikEJ**
fixes #734

### CODE REVIEW

File: src/DacpacTool/Extensions.cs [hunk 1]
```diff
@@ -82,10 +82,11 @@ public static string Format(this DacModelException exception, string fileName)
         {
             ArgumentNullException.ThrowIfNull(exception);
 
-            var stringBuilder = new StringBuilder();
+            var lines = new List<string>();
```
Comment (jmezach) [inline src/DacpacTool/Extensions.cs:85]: Can't we just call `AppendLine()` on the StringBuilder?

**Review by jeffrosenberg — APPROVED** [review]
